In [ ]:
import numpy as np
import pandas as pd
import os

# 1.1 Call sklearn libraries

# 1.1.1 Split data into train and test data
from sklearn.model_selection import train_test_split

# 1.1.2 PReprocessong:
from sklearn.preprocessing import StandardScaler

# 1.1.3 Import class DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier as dtree

# 1.1.4 To draw decision tree
from sklearn.tree import export_graphviz

# 1.1.5 Import iris
from sklearn.datasets import load_iris



# 1.1.7
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

In [2]:
import seaborn as sns

In [3]:
os.chdir("C:\\Users\\user\\Desktop\\ML Files")

In [4]:
df = pd.read_csv('Real_fake_news.csv')

In [5]:
df.head()

,Unnamed: 0,Unnamed: 0.1,author,statement,source,target,BinaryTarget,BinaryNumTarget
0,0,0,Jill Terreri,"New York is ""leading the nation with the lowes...",NYS Department of Corrections and Community Su...,True,REAL,1
1,1,1,Eleanor Hildebrandt,“Iowa ranks 45th in the U.S. for internet conn...,Cindy Axne,True,REAL,1
2,2,2,Emily Zirkelbach,“FUN FACT: West Virginia is home to zero billi...,David Gura,True,REAL,1
3,3,3,Madeline Heim,Says gubernatorial candidate Rebecca Kleefisch...,Kelda Helen Roys,True,REAL,1
4,4,4,Sabine Martin,"The Biden administration ""published a study co...",Randy Feenstra,True,REAL,1

In [6]:
df.tail()

,Unnamed: 0,Unnamed: 0.1,author,statement,source,target,BinaryTarget,BinaryNumTarget
4865,2431,2431,Bill McCarthy,"""Clinton campaign official arrested by FBI on ...",Bloggers,False,FAKE,0
4866,2432,2432,Miriam Valverde,"""Our courts find that 80 percent of those who ...",Jeff Sessions,False,FAKE,0
4867,2433,2433,Kiannah Sepeda-Miller,Says a progressive income tax proposal from De...,Evelyn Sanguinetti,False,FAKE,0
4868,2434,2434,Manuela Tobias,"""Maxine Waters Is Getting Criminally Charged!""",Bloggers,False,FAKE,0
4869,2435,2435,Bill McCarthy,"""Twitter caught leaking Donald Trump’s private...",Bloggers,False,FAKE,0

In [7]:
df.isnull().sum()

Unnamed: 0         0
Unnamed: 0.1       0
author             0
statement          0
source             0
target             0
BinaryTarget       0
BinaryNumTarget    0
dtype: int64

In [8]:
df = df.drop(columns=['Unnamed: 0','Unnamed: 0.1','target','BinaryTarget'])

In [9]:
df1 = pd.get_dummies(df)
df1.head()

,BinaryNumTarget,author_Aaron Marshall,author_Aaron Sharockman,author_Adam Thorp,author_Adrianne Uphold,author_Adriel Bettelheim,author_Al Bernardi,author_Alan Gathright,author_Alan Hovorka,author_Alayna Degenhardt,...,source_WrongWayRubio.com,source_Xavier Becerra,source_Yard sign,source_Yes On 62 campaign to abolish California's death penalty,source_YouTube videos,source_YourContent,source_Yvette McGee Brown,source_Zach Wahls,source_Zerlina Maxwell,source_teaparty.org
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
X = df1.drop(columns=['BinaryNumTarget'])
y = df1['BinaryNumTarget']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state=42)

In [12]:
ct = dtree(
           criterion="entropy",    # Alternative 'entropy'
           max_depth=None       # Alternative, specify an integer
                              # 'None' means full tree till single leaf
           )
# 5.1
ct.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [13]:
y_te = ct.predict(X_test)
np.sum((y_test == y_te))/y_test.size

0.891170431211499

In [14]:
fi = ct.feature_importances_
fi

array([0., 0., 0., ..., 0., 0., 0.])

In [15]:
from sklearn.ensemble import RandomForestClassifier

In [16]:
clf=RandomForestClassifier(n_estimators=100)

clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

In [17]:

from sklearn import metrics

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.893223819301848